## 1. Indicizzazione booleana
1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: 2, 3, 5, 7, 11, 13, 17, 19.

2. Utilizza un test logico (ad esempio >, <, ==, !=) per selezionare tutte le voci del vettore maggiori di 10.

3. Utilizza un test logico per selezionare tutti i numeri primi pari dalla lista.

In [26]:
import numpy as np

def primi(n):
    if n<2:
        return False
    for i in range(2,n):
        if n%i == 0:
            return False
    return True

arr = np.array([i for i in range(2,20) if primi(i)])
print("Vettore con numeri primi:", arr)

print("Maggiori di 10:", arr[arr>10])

print("Primi e pari:", arr[arr%2==0])


Vettore con numeri primi: [ 2  3  5  7 11 13 17 19]
Maggiori di 10: [11 13 17 19]
Primi e pari: [2]


## 2. Operazioni su array
Crea un array a, 2D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente la sua 2ª e 4ª riga, e c contenente solo la 3ª. Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [27]:
arr_bid = np.arange(30).reshape([5,6])
print("L'array bidimensionale è: \n", arr_bid)

b = arr_bid[[1,3]]
print("Array b:\n", b)

c = arr_bid[3]
print("Array c:\n", c)

# Divido ogni colonna di arr_bid con c (arrotondo)
print(np.round(arr_bid/c, 3))

L'array bidimensionale è: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Array b:
 [[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]
Array c:
 [18 19 20 21 22 23]
[[0.    0.053 0.1   0.143 0.182 0.217]
 [0.333 0.368 0.4   0.429 0.455 0.478]
 [0.667 0.684 0.7   0.714 0.727 0.739]
 [1.    1.    1.    1.    1.    1.   ]
 [1.333 1.316 1.3   1.286 1.273 1.261]]


## 3. Seleziona il numero più vicino a 0.5 in un array casuale
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1]. Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [28]:
np.random.seed(0) # Fisso (avrò sempre stessi numeri)
A = np.random.rand(10,3) # Genero matrice 10x3 con valori casuali in [0,1], ogni riga 3 numeri
print(A,"\n")

B = np.abs(A-0.5) # creo nuovo array con valore assoluto della distanza di ogni elemento da 0.5
print(B,"\n")

index = np.argmin(B, axis=1) # mi restituisce indici di ogni colonna con distanza minima da 0.5 (per ogni riga)
print(index, "\n")
print("Array contenente i numeri piu vicini a 0.5 per ogni riga:")
A[np.arange(A.shape[0]), index] # fancy indexing:  A[righe, colonne]

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329]
 [0.94466892 0.52184832 0.41466194]] 

[[0.0488135  0.21518937 0.10276338]
 [0.04488318 0.0763452  0.14589411]
 [0.06241279 0.391773   0.46366276]
 [0.11655848 0.29172504 0.02889492]
 [0.06804456 0.42559664 0.42896394]
 [0.4128707  0.4797816  0.33261985]
 [0.27815675 0.37001215 0.47861834]
 [0.29915856 0.03852064 0.28052918]
 [0.38172557 0.13992102 0.35664671]
 [0.44466892 0.02184832 0.08533806]] 

[0 0 0 2 0 2 0 1 1 1] 

Array contenente i numeri piu vicini a 0.5 per ogni riga:


array([0.5488135 , 0.54488318, 0.43758721, 0.52889492, 0.56804456,
       0.83261985, 0.77815675, 0.46147936, 0.63992102, 0.52184832])

## 4. Analisi della Frequenza Cardiaca con NumPy
1. Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca registrata dal tuo Fitbit durante la giornata:
68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70
Inserisci questi valori in un array NumPy.

2. Trova la frequenza cardiaca minima registrata durante la giornata.
(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)

3. Trova la frequenza cardiaca massima registrata durante la giornata.
(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)

4. Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120):
    - Crea un nuovo array che contiene True quando la frequenza cardiaca è superiore a 120, e False quando è inferiore o uguale a 120.
    - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.
 

In [33]:
freq = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

print(np.min(freq))
print(np.max(freq))

arr_bool = freq>120 # True se maggiore, False se minore
print(arr_bool)

percent = np.round((np.sum(arr_bool) / len(arr_bool)) * 100,2)
print(percent,"%")


60
164
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
52.38 %


# 5. Manipolazione di vettori
1. Creare un vettore contenente i seguenti stipendi: 50.000, 105.250, 55.000, 89.000.
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna 105.250 dollari, riceva un aumento del 15%.

3. Il 115% di 105.250 dollari è 121.037,50 dollari.
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento dtype in modo che, quando il CEO riceve un aumento del 15%, il suo stipendio finale sia esattamente 121.037,50 dollari.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (50.000 dollari), che ora pretende un aumento del 20%.
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del 10%.
Modifica il vettore di conseguenza.

7. Calcola il costo totale del personale dopo tutti gli aumenti.
Alla fine, quanto è costato all'azienda l'aumento di circa 16.000 dollari del CEO?

In [ ]:
# 1
stipendi = np.array([50000, 105250, 55000, 89000])
print("Gli stipendi sono: ", stipendi)
costo_tot = stipendi.sum()
print(f"Il costo totale del personale è {costo_tot}$")

# 2
stipendi[1] *= 1.15 # Aumento CEO del 15%
print("Gli stipendi con l'aumento del CEO sono:", stipendi)

# 3
stipendi.dtype
# Il valore 121037,50 non è presente perchè il tipo degli elementi del vettore è int64 e io sto cercando un float

# 4
stipendi = np.array([50000, 105250, 55000, 89000], dtype=float)
stipendi[1] *= 1.15
print("Gli stipendi con l'aumento del CEO (float) sono:", stipendi)

# 5
stipendi[0] *= 1.20
print("Stipendi con aumento dell'impiegata infastidita:", stipendi)

# 6
stipendi[(stipendi != stipendi[0]) & (stipendi != stipendi[1])] *= 1.10
print("Tutti gli stipendi aumentati: ", stipendi)

# 7
finale = stipendi.sum()
print(f"Costo totale del personale dopo tutti gli aumenti: {finale}$")

costo_extra = finale - costo_tot
print(f"L'aumento totale è costato: {costo_extra}$")

Gli stipendi sono:  [ 50000 105250  55000  89000]
Il costo totale del personale è 299250$
Gli stipendi con l'aumento del CEO sono: [ 50000 121037  55000  89000]
Gli stipendi con l'aumento del CEO (float) sono: [ 50000.  121037.5  55000.   89000. ]
Stipendi con aumento dell'impiegata infastidita: [ 60000.  121037.5  55000.   89000. ]
Tutti gli stipendi aumentati:  [ 60000.  121037.5  60500.   97900. ]
Costo totale del personale dopo tutti gli aumenti: 339437.5$
L'aumento totale è costato: 40187.5$


# 6. Valori di Co2
1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18 tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [ ]:
#1
emissioni = np.loadtxt("emissioni.txt")

#2
sopra_soglia = emissioni[emissioni > 18]
conta_val = sopra_soglia.size
print("Valori sopra 18 tonnellate:", conta_val)

media_sopra = np.round(sopra_soglia.mean(), 3)
print("Media delle emissioni sopra 18 tonnellate:", media_sopra)

#3
frazione = np.round(sopra_soglia.sum() / emissioni.sum(), 3)
print("Frazione totale di emissioni sopra la soglia:", frazione)

Valori sopra 18 tonnellate: 35
Media delle emissioni sopra 18 tonnellate: 19.031
Frazione totale di emissioni sopra la soglia: 0.267



# 7. Analisi di una matrice
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])

1. Seleziona dalla matrice solo gli intervistati con almeno 12 anni di istruzione utilizzando un test logico.

2. In un'unica riga di codice, seleziona i redditi degli intervistati con almeno 12 anni di istruzione.

3. In un'unica riga di codice, calcola il reddito medio degli intervistati con almeno 12 anni di istruzione.

In [ ]:
survey_matrix = np.array([ [25, 40000, 10],
                           [32, 52000, 12],
                           [40, 63000, 14],
                           [29, 47000, 11], 
                           [35, 58000, 13] ])
# colonna 0 = età, colonna 1 = reddito, colonna 2 = anni di istruzione

#1
print(f"Intervistati con almeno 12 anni di istruzione: \n {survey_matrix[survey_matrix[:, 2] >= 12]}") 
# seleziono tutte le righe in cui la colonna 2 (anni di istruzione) è ≥ 12

#2
print(f"Redditi di chi ha almeno 12 anni di istruzione: \n {survey_matrix[survey_matrix[:, 2] >= 12, 1]}")
# Seleziono i redditi (colonna 1) degli intervistati con almeno 12 anni di istruzione

# 3
print(f"Reddito medio di chi ha almeno 12 anni di istruzione: {np.round(survey_matrix[survey_matrix[:, 2] >= 12, 1].mean(),2)}")
# Calcolo il reddito medio degli intervistati con almeno 12 anni di istruzione

Intervistati con almeno 12 anni di istruzione: 
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
Redditi di chi ha almeno 12 anni di istruzione: 
 [52000 63000 58000]
Reddito medio di chi ha almeno 12 anni di istruzione: 57666.67


# 8. Rimpiazzare gli outliers
Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con 500 cittadini di 55 anni e oltre.

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare il cittadino più anziano.

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età 999 invece dell'età corretta.

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.

In [34]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])
pulito = ages[ages != 999]
print(pulito)
max = np.max(pulito)
print(f"L'età del cittadino più anziano è: {max}")

[ 92 108  75  63  62  66  90  98  97  92  60 107  90  71  97  86  55  55
  98  57  96 104  96  94  72  98 111  98  89  69  77  92  85 101  93 100
  90 101  96  98  87 106  86 108  55  67  65  68  59  67  72  57  79  95
  67  86  70  91 111  67  75  59  88  90  99  94  65 111 103 100  70  63
  65 100 110  70  57  75  56 104 111  90  74 100  90  86  88  99  58 103
  88 103  64  96 105  89  83  65 100  62  73 105  83 105  58  96  77  74
  95 109  91 101  91  63 111  97 108  75  77  73  58  94  83  90  61 110
 107 105  85  64  66  71 107 105  72  78  66 100 102  72  74  68  73  72
  90  93  99  55  92  83  58  71  89  75  98  87  78  97  71 106  83  58
  81 100  72  93  70  65  60  95 107  94  77  87  90  82  56  99 107  86
  56  73  96  64  69  64  92  57 104 110  69  66  68  84  89  72  80  55
  75  87  57 106  69  66  62 102  76 111  96  83  84  61 102  63 107  63
  76  58  83  58  61  71  77  90  74 100 103  74  92 102  63  87  93  61
  63  86  74  98  64  78  95  84  81 107  85  79  8

# 9.Generazione random di storie
Usando la lista qui sotto, estrai casualmente 5 parole con reinserimento (cioè, i duplicati sono ammessi).

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."

In [ ]:
import random

lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

parole = [lista_parole[random.randint(0, len(lista_parole)-1)] for i in range(5)]
print(parole)


print("In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico", parole[0], "che proteggeva.")
print("Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante")
print("e le offrì il", parole[1], "come dono, i suoi occhi si spalancarono e lei esclamò una sola parola:", '"' + parole[2] + '".')
print("Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un", parole[3] + ".")
print("Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.")
print("Con un sorriso da un orecchio all'altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:")
print('"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza', parole[4] + '!"')
print("Ci fu grande gioia e celebrazione.")

['BENEFICIARIO', 'ALFABETIZZAZIONE', 'IMPERO', 'APPLICAZIONE', 'BENEFICIARIO']
In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico BENEFICIARIO che proteggeva.
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante
e le offrì il ALFABETIZZAZIONE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola: "IMPERO".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un APPLICAZIONE.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all'altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza BENEFICIARIO!"
Ci fu grande gioia e celebrazione.
