## 1. Trasformare cicli in list comprehension
Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
# creazione lista con elementi da 0 a 9
lista = []
for i in range(0,10):
    lista.append(i)
print(lista)

lista_comp = [i for i in range(0,10)]
print(lista_comp)

# creazione lista con i quadrati di ogni elemento da 1 a 10
lista_2 = []
for i in range(1,11):
    lista_2.append(i**2)
print(lista_2)
lista_comp_2 = [i**2 for i in range(1,11)]
print(lista_comp_2)

# crea lista numeri pari
lista_3 = []
for i in range(1,21):
        if i%2 == 0:
            lista_3.append(i)
lista_comp_3 = [i for i in range(1,21) if i%2 == 0]
print(lista_3)
print(lista_comp_3)

#

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


## 2. Vettore di Numeri Primi
1. Crea un vettore contenente tutti i numeri primi compresi tra 0 e 10
   (Puoi scriverli direttamente nell'array).

2. Conta quanti numeri ci sono nel vettore utilizzando la funzione len(). Ottieni lo stesso numero accedendo all'attributo .size del vettore.

3. Quale pensi sia il tipo di dato (dtype) del vettore? Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo
   all'attributo .dtype del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi.

In [ ]:
import numpy as np
def primi(n):
    if n<2:
        return False
    for i in range(2,n):
        if n%i == 0:
            return False
    return True

listaa = []
for i in range(0,11):
    if primi(i):
        listaa.append(i)

array = np.array(listaa)
print(array)
length = len(array)
print(length)
array.dtype #Sarà di tipo intero

array_comp = np.array([n for n in range(0,11) if primi(n)])
print(array_comp)


[2 3 5 7]
4
[2 3 5 7]


## 3. Operazioni su array
Crea un array a, 1D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente una sottostringa a piacere 
e c che è il reverse dell'array a (esempio [1,2,3] diventa [3,2,1]) . Dividi l'array a per l'array c. Fai la stessa cosa per una lista.

In [1]:
import numpy as np
a = np.arange(1,12)
b = a[3:10]
c = a[::-1]
print(a)
print(b)
print(c)
array_div = a/c
array_div = np.round(array_div,2)

print(array_div)

# VERSIONE CON LISTE
lista_a = list(range(1,12))
lista_b = lista_a[3:10]
lista_c = lista_a[::-1]

print(lista_a)
print(lista_b)
print(lista_c)

lista_div = []
for i in range(len(lista_a)):
    lista_div.append(round(lista_a[i]/lista_c[i],2))
print(lista_div)


[ 1  2  3  4  5  6  7  8  9 10 11]
[ 4  5  6  7  8  9 10]
[11 10  9  8  7  6  5  4  3  2  1]
[ 0.09  0.2   0.33  0.5   0.71  1.    1.4   2.    3.    5.   11.  ]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[4, 5, 6, 7, 8, 9, 10]
[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.09, 0.2, 0.33, 0.5, 0.71, 1.0, 1.4, 2.0, 3.0, 5.0, 11.0]
